### ISSUE TITLE
Compare signal yields between kevin and thong too

### ISSUE THREAD

**Issue by sixie** [cms-lpc-llp/DelayedPhotonLimit#3]

**Comment by thongonary** [comment]
| L=200, ctau=10    | Kevin   | Thong   | Thong-Kevin | (Thong-Kevin)/Kevin |
|-----------------|---------|---------|-------------|---------------------|
| Cuts            |         |         |             |                     |
| >= 1 EB photon  | 1589.77 | 1656.25 | 66.48       | 4.18%               |
| photonPT        | 1527.08 | 1602.98 | 75.9        | 4.97%               |
| METFilter       | 1503.52 | 1578.07 | 74.55       | 4.96%               |
| photonR9        | 1212.47 | 1243.8  | 31.33       | 2.58%               |
| photonTrackVeto | 938.63  | 962.02  | 23.39       | 2.49%               |
| photonHoverE    | 921.15  | 944.02  | 22.87       | 2.48%               |
| photonIetaIeta  | 920.3   | 943.18  | 22.88       | 2.49%               |
| photonSminor    | 920.34  | 943.11  | 22.77       | 2.47%               |
| photonSmajor    | 920.19  | 943.11  | 22.92       | 2.49%               |
| photonIsolation | 646.14  | 731.05  | 84.91       | 13.14%              |
| nJets           | 504.12  | 554.96  | 50.84       | 10.08%              |
| HT              | 309.44  | 338.97  | 29.53       | 9.54%               |
| Trigger         | 306.43  | 335.68  | 29.25       | 9.55%               |


| L=200, ctau=200   | Kevin   | Thong   | Thong-Kevin | (Thong-Kevin)/Kevin |
|-----------------|---------|---------|-------------|---------------------|
| Cuts            |         |         |             |                     |
| >= 1 EB photon  | 1387.95 | 1392.52 | 4.57        | 0.33%               |
| photonPT        | 1175.57 | 1255.19 | 79.62       | 6.77%               |
| METFilter       | 982.39  | 1046.21 | 63.82       | 6.50%               |
| photonR9        | 640.54  | 651.16  | 10.62       | 1.66%               |
| photonTrackVeto | 488.28  | 496.23  | 7.95        | 1.63%               |
| photonHoverE    | 478.39  | 486.69  | 8.3         | 1.73%               |
| photonIetaIeta  | 463.1   | 470.4   | 7.3         | 1.58%               |
| photonSminor    | 462.75  | 469.91  | 7.16        | 1.55%               |
| photonSmajor    | 462.54  | 469.91  | 7.37        | 1.59%               |
| photonIsolation | 311.41  | 350.72  | 39.31       | 12.62%              |
| nJets           | 226.99  | 250.27  | 23.28       | 10.26%              |
| HT              | 129.62  | 141.45  | 11.83       | 9.13%               |
| Trigger         | 127.09  | 138.63  | 11.54       | 9.08%               |



| L=200, ctau=1200  | Kevin   | Thong   | Thong-Kevin | (Thong-Kevin)/Kevin |
|-----------------|---------|---------|-------------|---------------------|
| Cuts            |         |         |             |                     |
| >= 1 EB photon  | 1125.63 | 1035.71 | -89.92      | -7.99%              |
| photonPT        | 763.59  | 843.19  | 79.6        | 10.42%              |
| METFilter       | 692.52  | 763.55  | 71.03       | 10.26%              |
| photonR9        | 317.59  | 321.58  | 3.99        | 1.26%               |
| photonTrackVeto | 141.81  | 142.28  | 0.47        | 0.33%               |
| photonHoverE    | 138.58  | 139.41  | 0.83        | 0.60%               |
| photonIetaIeta  | 134.14  | 134.14  | 0           | 0.00%               |
| photonSminor    | 134.09  | 134.1   | 0.01        | 0.01%               |
| photonSmajor    | 134.02  | 134.1   | 0.08        | 0.06%               |
| photonIsolation | 90.07   | 99.03   | 8.96        | 9.95%               |
| nJets           | 62.26   | 66.82   | 4.56        | 7.32%               |
| HT              | 35.59   | 37.46   | 1.87        | 5.25%               |
| Trigger         | 34.7    | 36.61   | 1.91        | 5.50%               |


Takeaway: The differences are all less than 13%. I mostly get better signal efficiency than Kevin for some reason.

**Comment by thongonary** [comment]
Because @cmorgoth asked about signal trigger efficiency, here is an approximation. The `None` here actually already has the preselection of 2 photons > 40 GeV. Taking with a grain of salt, the signal trigger efficiency is around 40%.

Model L300TeV_Ctau200cm
xsecBR = 0.004429
sumWeights = 93700.0
+ None: 121.61 (100.00%)
+ Trigger: 49.59 (40.78%)
+ nPhoton>1: 45.85 (37.70%)
+ photonIsEB: 45.85 (37.70%)
+ photonPT>70: 45.59 (37.49%)
+ photonR9>0.9: 35.51 (29.20%)
+ photonHoverE<0.046: 35.11 (28.87%)
+ photonIetaeta<0.014: 34.04 (27.99%)
+ photonIsolationLoose: 28.37 (23.33%)
+ photonSminor<0.4: 28.36 (23.32%)
+ nJets>2: 18.84 (15.49%)

Model L400TeV_Ctau200cm
xsecBR = 0.0007784
sumWeights = 100001.3125
+ None: 22.36 (100.00%)
+ Trigger: 9.68 (43.27%)
+ nPhoton>1: 9.09 (40.63%)
+ photonIsEB: 9.09 (40.63%)
+ photonPT>70: 9.06 (40.51%)
+ photonR9>0.9: 7.19 (32.14%)
+ photonHoverE<0.046: 7.12 (31.84%)
+ photonIetaeta<0.014: 6.91 (30.90%)
+ photonIsolationLoose: 5.84 (26.10%)
+ photonSminor<0.4: 5.83 (26.09%)
+ nJets>2: 3.87 (17.29%)

**Comment by cmorgoth** [comment]
ok, so I guess all signal comes with a photon so it's more or less ok. It's the eta requirement on EB to in your pre-selection?  If not I would say the trigger is pretty efficient for signal since I expect you to loose events just cause of acceptance. I think this is telling us that the trigger is not the limiting factor.

**Comment by thongonary** [comment]
This is from @zhangzc11's ntuple (`/mnt/hadoop/store/group/phys_susy/razor/Run2Analysis/DelayedPhotonAnalysis/2016/orderByPt/withcut/GMSB_L400TeV_Ctau200cm_13TeV-pythia8.root`) so I'm not 100% sure, but looks like there is no EB requirement. Also this is 2016 trigger.
